### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by vaibhav90** [mitchd/usrp-utils#1]
Hi, 

I tried to build the suite, however the build process is failing due to following errors. 
![build](https://cloud.githubusercontent.com/assets/7610904/5916509/40c97730-a612-11e4-8cc5-2d0b9a4f1458.png)

Kindly let me know, how to fix it. I appreciate the help. 

-Vaibhav

**Comment by mitchd** [comment]
Thanks for bringing this to my attention.

It looks like the latest GCC handles complex float a little differently
than when I had originally made these libraries.  I'll do some
investigation to determine how to resolve this.  It's not quite as simple
as replacing every instance of "complex float" with "_Complex float" or
"complex<float>"

"complex float" is a C construct, as opposed to the std::complex<type>
abstract data type.

I'll see what I can do here, but feel free to try some different
definitions of the complex type.  If you find something that builds, send a
patch or a pull request and I'll merge it.

-Mitch

**Comment by vaibhav90** [comment]
Hi, 

Thanks for the reply. Ok, I will try to fix it. I will let you know if its building. 

-Vaibhav

**Comment by mitchd** [comment]
Finally updated the build process and code.
